### ISSUE TITLE
关于该镜像的一些咨询和建议

### ISSUE THREAD

**Issue by Inetgeek** [hu3rror/memos-on-fly#1]
感谢大佬给出这样的免费部署方案，但是在使用过程中因为不熟悉该工具及相关的工具，因此想咨询您一些关于memos-on-fly库的问题：
1.这里面使用的B2存储库只是单纯备份fly.io上的数据，还是将fly.io上部署的memos用户产生的数据存到B2里，然后在用户前端访问memos时从B2中取出数据呢？
2.B2的备份是自动的吗？
3.能否支持设置图床的功能？毕竟免费资源的容量有限，而且是写到数据库里的，加载和渲染的代价比直接存储图床要高。
谢谢！

**Comment by hu3rror** [comment]
这个项目是基于 litestream 这个工具的
1. 两者其实是紧密结合的，不是单纯的备份关系。fly.io 上的数据会通过 litestream 备份到 B2 bucket 中，若 fly. io 上的硬盘损坏或出现特殊情况导致 memos_prod.db 丢失，那在 fly.io 的服务重启后，会自动从 B2 bucket 重新恢复到最后备份的数据，不需要人为干预。关于 litestream 是怎么运作的务必参考：https://litestream.io/how-it-works/
2. litestream 检测到 fly.io 的数据更改后会自动备份，更具体的内容还是看上面的链接
3. 图床功能请向 memos 上游反馈：https://github.com/usememos/memos/issues/new/choose
