### ISSUE TITLE
Failed to fetch the image from "docker.io/hu3rror/memos-fly:latest

### ISSUE THREAD

**Issue by Inetgeek** [hu3rror/memos-on-fly#2]
![image](https://user-images.githubusercontent.com/42563262/213919396-dade9bd7-b9b6-40ac-9743-6a6eb689bd18.png)
旧版的可以用，比如0.10.1版本可以正常使用`flyctl deploy'，但是新版则会出现上图的错误。

**Comment by hu3rror** [comment]
https://github.com/hu3rror/memos-on-fly-build/issues/1#issuecomment-1399403747
