### ISSUE TITLE
After updating to version 0.13.0, the media file thumbnail attached to the post will not be displayed

### ISSUE THREAD

**Issue by heronaly** [hu3rror/memos-on-fly#4]
你好，我用你的镜像就缩略图不显示了
在这里也已经报告过了
https://github.com/usememos/memos/issues/1692

但是他们说已经解决的问题
你这个镜像和他们的有啥区别
麻烦您
谢谢

**Comment by hu3rror** [comment]
已经同步最新的更改，等待即可（可自行查看 Actions 的情况），之后可重新拉最新的镜像
