### ISSUE TITLE
How to migrate from the no litestream version to the version with litestream?

### ISSUE THREAD

**Issue by inertia42** [hu3rror/memos-on-fly#7]
Since I am unfamiliar with Memos, I chose the version without litestream for deployment. After using it for some time, I've come to realize the significance of having a backup. Therefore, I would like to switch from the non-litestream version to the litestream version. How can I accomplish this?

Can I use `flyctl ssh console` to connect to the container, back up its database files and asset folder, and then upload them to the new deployment?

Thank you.

**Comment by hu3rror** [comment]
memos-litestream is actually based on the official memos image with the addition of litestream. In other words, this is just a prepositive startup and does not involve invasive hacker modifications.

Therefore, you can very simply follow the litestream README.md tutorial on the project's homepage to reoperate. Change the image source to `ghcr.io/hu3rror/memos-litestream:stable`, and also complete other operations such as adding litestream-related variables.

Oh, by the way, remember to use `fly ssh sftp` to back up all data before performing any operations to avoid unnecessary data loss.

**Comment by inertia42** [comment]
It works! Thank you for your help.
